version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    depends_on:
      - db
      - rabbitmq
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/db
      RABBITMQ_URL: amqp://rabbitmq:5672
    deploy:
      replicas: 2

  notification-service:
    build: ./notification-service
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://rabbitmq:5672
    deploy:
      replicas: 2

  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest  
    command: >
      sh -c "
        apt-get update && apt-get install -y wget &&
        wget -O /opt/rabbitmq/plugins/rabbitmq_delayed_message_exchange-4.1.0.ez https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v4.1.0/rabbitmq_delayed_message_exchange-4.1.0.ez &&
        rabbitmq-plugins enable rabbitmq_delayed_message_exchange &&
        rabbitmq-server
      "

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
